Update build process to verify makeappx.exe in Windows Kit path

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -22,10 +22,18 @@ jobs:
       run: choco install windows-sdk-10-version-2004-all -y
       shell: pwsh
 
-    - name: Get Windows Kit Path
+    - name: Get Windows Kit Path and Verify makeappx.exe
       run: |
         $windowsKitPath = (Get-ItemProperty 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots').'KitsRoot10'
-        echo "Windows Kit Path: ${windowsKitPath}bin\x64"
-        echo "WINDOWS_KIT_PATH=${windowsKitPath}bin\x64" >> $GITHUB_ENV
+        $makeappxPath = Join-Path -Path $windowsKitPath -ChildPath 'bin\x64\makeappx.exe'
+        if (Test-Path $makeappxPath) {
+            echo "Windows Kit Path: $windowsKitPath"
+            echo "makeappx.exe found at $makeappxPath"
+            echo "WINDOWS_KIT_PATH=${windowsKitPath}bin\x64" >> $GITHUB_ENV
+        } else {
+            Write-Error "makeappx.exe not found in Windows Kit Path."
+            exit 1
+        }
       shell: pwsh
+
 
