Update build process to include generating dev certificate, installing dependencies, and building the app

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -23,13 +23,31 @@ jobs:
         choco install microsoft-build-tools -y
       shell: pwsh
 
-    - name: Install dependencies
-      run: npm install
+    - name: Verify makeappx.exe and build & sign the appx
+      run: |
+        # Verify makeappx.exe
+        $makeappxPath = 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit\makeappx.exe'
+        if (Test-Path $makeappxPath) {
+          echo "makeappx.exe found at $makeappxPath"
+          $env:WINDOWS_KIT_PATH="C:\Program Files (x86)\Windows Kits\10\App Certification Kit"
+        } else {
+          Write-Error "makeappx.exe not found."
+          exit 1
+        }
 
-    - name: Build app
-      run: npm run make
+        # Install dependencies
+        npm install
+
+        # Provide environment variables for signing during the build
+        $env:CERT_PATH=$certPath
+        $env:CERT_PASSWORD=$certPassword
+
+        # Build and sign the appx using Electron Forge
+        npm run make
       env:
         WINDOWS_KIT_PATH: ${{ env.WINDOWS_KIT_PATH }}
+        CERT_PATH: ${{ env.CERT_PATH }}
+        CERT_PASSWORD: ${{ env.CERT_PASSWORD }}
       shell: pwsh
 
     - name: Extract version from package.json
